GloboTicket/GloboTicket.Client/Models/BasketLineViewModel.cs
using System;

namespace GloboTicket.Client.Models
{
    public class BasketLineViewModel
    {
        public Guid EventId { get; set; }
        public string EventName { get; set; }
        public decimal Price { get; set; }
        public int Quantity { get; set; }
    }
}

GloboTicket/GloboTicket.Client/Models/ErrorViewModel.cs
using System;

namespace GloboTicket.Client.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

GloboTicket/GloboTicket.Client/Models/Settings.cs
using System;

namespace GloboTicket.Web.Models
{
    public class Settings
    {
        public string BasketIdCookieName => "BasketId";
        public  Guid UserId => Guid.Parse("{E455A3DF-7FA5-47E0-8435-179B300D531F}");
    }
}

GloboTicket/GloboTicket.Client/Models/View/ErrorViewModel.cs
using System;

namespace GloboTicket.Web.Models.View
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

GloboTicket/GloboTicket.Client/Models/View/EventListModel.cs
using System;
using System.Collections.Generic;
using GloboTicket.Grpc;

namespace GloboTicket.Web.Models.View
{
    public class EventListModel
    {
        public IEnumerable<Event> Events { get; set; }
        public Guid SelectedCategory { get; set; }
        public IEnumerable<Category> Categories { get; set; }
    }
}

GloboTicket/GloboTicket.Client/Controllers/EventCatalogController.cs
using System;
using System.Threading.Tasks;
using GloboTicket.Grpc;
using GloboTicket.Web.Models.View;
using Microsoft.AspNetCore.Mvc;

namespace GloboTicket.Web.Controllers
{
    public class EventCatalogController : Controller
    {
        private readonly Events.EventsClient eventCatalogService;

        public EventCatalogController(Events.EventsClient eventCatalogService)
        {
            this.eventCatalogService = eventCatalogService;
        }

        public async Task<IActionResult> Index(Guid categoryId)
        {
            var getCategories = eventCatalogService.GetAllCategoriesAsync(new GetAllCategoriesRequest());
            var getEvents = categoryId == Guid.Empty ? eventCatalogService.GetAllAsync(new GetAllEventsRequest()) :
                eventCatalogService.GetAllByCategoryIdAsync(new GetAllEventsByCategoryIdRequest { CategoryId = categoryId.ToString() });
            await Task.WhenAll(new Task[] { getCategories.ResponseAsync, getEvents.ResponseAsync });

            return View(
                new EventListModel
                {
                    Events = getEvents.ResponseAsync.Result.Events,
                    Categories = getCategories.ResponseAsync.Result.Categories,
                    SelectedCategory = categoryId
                }
            );
        }

        [HttpPost]
        public IActionResult SelectCategory([FromForm]Guid selectedCategory)
        {
            return RedirectToAction("Index", new { categoryId = selectedCategory });
        }

        public async Task<IActionResult> Detail(Guid eventId)
        {
            var ev = await eventCatalogService.GetByEventIdAsync(new GetByEventIdRequest { EventId = eventId.ToString() });
            return View(ev.Event);
        }
    }
}

GloboTicket/GloboTicket.Client/Views/EventCatalog/Detail.cshtml
@model GloboTicket.Grpc.Event
<div class="row mt-5">
    <div class="col-md-4">
        <img src="@Model.ImageUrl" class="detailImage" alt="Artist pic" />
    </div>
    <div class="col-md-6 ml-1">
        <div class="row">
            <div class="columnHeader">@Model.CategoryName.ToUpper()</div>
        </div>
        <div class="row mt-2 bold">
            <h1>@Model.Name</h1>
        </div>
        <div class="row mt-2">
            <h3>@Model.Artist</h3>
        </div>
        <div class="row mt-3 mt-4 bold">
            <h3>@Model.Date.ToDateTime().ToShortDateString()</h3>
        </div>
        <div class="row mt-4">
            @Model.Description
        </div>
        <div class="row mt-5">
            <h3><span class="bold">$@Model.Price</span></h3><span class="mt-1">&nbsp;&nbsp;&nbsp; PER TICKET</span>
        </div>
    </div>
</div>
<div class="row mt-5">
    <div class="col">
        <hr />
    </div>
</div>

GloboTicket/GloboTicket.Client/Views/EventCatalog/DisplayTemplates/Event.cshtml
@model GloboTicket.Grpc.Event
<tr>
    <td>
        <img class="artistPic" src="@Model.ImageUrl" alt="Artist pic" />
    </td>
    <td>
        @Model.Date.ToDateTime().ToShortDateString()
    </td>
    <td>
        @Model.Name
    </td>
    <td>
        @Model.Artist
    </td>
    <td class="bold big">
        $@Model.Price
    </td>
    <td>
        <a class="btn-primary" type="button" asp-action="Detail" asp-route-eventId="@Model.EventId">PURCHASE DETAILS</a>
    </td>
</tr>

GloboTicket/GloboTicket.Client/Views/EventCatalog/DisplayTemplates/EventDto.cshtml
@model GloboTicket.EventCatalogService.EventDto
<tr>
    <td>
        <img class="artistPic" src="@Model.ImageUrl" alt="Artist pic" />
    </td>
    <td>
        @Model.Date
    </td>
    <td>
        @Model.Name
    </td>
    <td>
        @Model.Artist
    </td>
    <td>
        $@Model.Price
    </td>
    <td>
        <a asp-controller="ShoppingBasket" asp-action="AddToBasket" asp-route-eventId="@Model.EventId">Buy ticket</a>
    </td>
</tr>
<tr>
    <td colspan="5">
        @Model.Description
    </td>
</tr>

GloboTicket/GloboTicket.Client/Views/EventCatalog/Index.cshtml
@model GloboTicket.Web.Models.View.EventListModel

@{
    var categoryListItems = Model.Categories.Select(c =>
        new SelectListItem { Value = c.CategoryId.ToString(), Text = c.Name }
    ).ToList();
    categoryListItems.Insert(0, new SelectListItem { Text = "All" });
}

<div class="row mt-5 mb-3">
    <form asp-action="SelectCategory" method="post">
        <select asp-for="SelectedCategory" asp-items="categoryListItems"></select>
        <button type="submit" class="filterButton">FILTER</button>
    </form>
</div>

<div class="row">
    @if (Model.Events.Count() == 0)
    {
        <text>No events were found.</text>
    }
    else
    {
        <table class="table">
            <thead>
                <tr class="columnHeader">
                    <th></th>
                    <th>DATE</th>
                    <th>NAME</th>
                    <th>ARTIST</th>
                    <th>PRICE</th>
                </tr>
            </thead>
            <tbody>
                @Html.DisplayFor(m => m.Events)
            </tbody>
        </table>
    }
</div>

@section Widget {

}

GloboTicket/GloboTicket.Client/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GloboTicket</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <div class="container">
            <div class="row mb-3 pb-3 pt-3">
                <div class="col-md-9">
                    <a class="navbar-brand" asp-controller="EventCatalog" asp-action="Index">
                        <img src="~/img/_Export_globoticket-horizontal-white.png" />
                    </a>
                </div>

                <div class="col-md-3 mt-5">
                    <div>
                        @RenderSection("Widget", required: false)
                    </div>
                </div>
            </div>
        </div>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @RenderSection("Scripts", required: false)
</body>
</html>

GloboTicket/GloboTicket.Client/Views/ShoppingBasket/Thanks.cshtml
<p class="bold big">Thank you!</p>
<p>Your order is submitted for payment. <br />
We will notify you as soon as payment is complete.</p>